---
- name: Generate the host mapping for adding node to cluster
  set_fact:
    host_mapping_template: "{{ lookup('template', 'host_mapping_file.json.j2', convert_data=False) }} "

- name: Print the host mapping
  debug:
    var: host_mapping_template|from_json
    verbosity: 1


- name: "expand cluster by adding node {{ ansible_fqdn }}"
  uri:
    url: "http://{{ hostvars[groups['ambari-server']|sort|list|first]['ansible_fqdn'] }}:8080/api/v1/clusters/{{ cluster_name }}/hosts/{{ ansible_fqdn }}"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_admin_user }}"
    password: "{{ ambari_admin_password }}"
    headers: '{"X-Requested-By":"ambari"}'
    body: " {{ host_mapping_template }}"
    body_format: raw
    status_code: 200,201,202
    timeout: 120
    return_content: yes
    register: cluster_expand_task
  ignore_errors: yes

