# tasks for common role
---

- hostname:
    name: "{{ inventory_hostname }}"
  become: yes
  when: ansible_hostname_as_actual

- import_tasks: hosts.yml
  when: not external_dns

- name: remove invalid mapping of hostname to loopback address (e.g. vagrant change host capabililty)
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    state: absent
  become: yes

- name: add back removed valid loopback address mapping to localhost
  lineinfile:
    path: /etc/hosts
    insertbefore: BOF
    line: '127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4'
    state: present
  become: yes

- name: install yum utilities for recovery from yum failure
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
  become: yes
  when: ansible_os_family|lower == 'redhat'

- name: install useful os utilities and packages
  import_tasks: useful_utilities.yml

- name: install java
  import_tasks: java_install.yml
  when: java != "embedded"

- import_tasks: sudoer.yml

- include_tasks: users.yml
  with_items: "{{ passwordless_ssh_users }}"
  loop_control:
    loop_var: ssh_user
  tags:
    user_ssh_keys

- import_tasks: time_ntp.yml
  tags: ntp

# Selinux incurs a 7-10% performance penalty on a Hadoop cluster
- name: disable selinux (not recommended in real setup for security reasons)
  selinux:
    state: disabled
  become: yes
  tags: selinux

- import_tasks: firewall.yml

- name: set umask on all using profile.d
  copy:
    src: ../templates/set_umask.sh
    dest: /etc/profile.d/set_umask.sh
    mode: 0755
  become: yes

# recommended by Cloudera to diable ipv6
- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  become: yes
