# configure timezone and ntp
---
- name: set timezone
  shell: timedatectl set-timezone Asia/Singapore
  become: yes

- name: make sure NTP is stopped
  systemd: name=ntpd state=stopped enabled=yes
  become: yes
  tags: ntp

- name: make sure NTP is started up
  systemd:
    name: "{{ ntp_service_name }}"
    state: started
  become: yes
  tags: ntp

- name: make sure NTP is enabled
  systemd:
    name: "{{ ntp_service_name }}"
    enabled: yes
  ignore_errors: true
  become: yes
  tags: ntp

- name: Sync hwclock
  shell: hwclock -w
  become: yes
  tags: ntp
