
- name: install epel release (if online)
  yum:
    name: epel-release
    state: present
  become: yes
  when: is_online

- name: install other basic os utilities
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ base_os_packages | join(',') }}"
  become: yes
