---
- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: (ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int == 7)
  become: yes

- name: Restart ambari-agent
  systemd:
    name: ambari-agent
    state: restarted
  become: yes
