# python library setup
---
- name: install python packages for data science
  pip:
    name: "{{ item }}"
  with_items:
    - pytest
    - pyyaml
    - colorama
    - numpy
    - nltk
    - pandas
  become: yes

- name: install NLTK data
  shell: "python -m nltk.downloader -d {{ nltk_data_dir }} {{ item }}"
  with_items: "{{ nltk_data_package }}"
  args:
    creates: "{{ nltk_data_dir }}"
  become: yes
