# tasks for ambari server role
---
- name: install ambari-server
  yum:
    name: ambari-server
    update_cache: yes
    state: latest
  notify: Reload systemd
  become: yes

- name : create ambari install folder
  file : dest=/opt/ambari-install state=directory mode=0755
  become: yes

- name: configure ambari-server
  shell: ambari-server setup --enable-lzo-under-gpl-license -s > /tmp/ambari-install-output
  args:
    creates: /opt/ambari-install/ansible.done
    executable: /bin/bash
  become: yes

- name : check if ambari-server is installed
  wait_for : path=/tmp/ambari-install-output search_regex="completed successfully"

- name : start ambari server and enabled at reboot
  systemd : name=ambari-server state=restarted enabled=yes
  become: yes

- name : check if ambari-server is up
  wait_for : host=127.0.0.1 port=8080 delay=10
