---
# tasks for base role

- hostname:
    name: "{{ inventory_hostname }}"
  become: yes
  when: ansibe_hostname_as_actual

- name: install yum utilities
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
  become: yes

- import_tasks: sudoer.yml

- include_tasks: users.yml
  with_items: "{{ passwordless_ssh_users }}"
  loop_control:
    loop_var: ssh_user
  tags:
    user_ssh_keys

# - name: Install NTP
#   yum:
#     name: "{{ item }}"
#     state: present
#     with_items:
#       - ntp
#   tags: ntp

# handlers:
#     - name: restart ntp
#       service: name=ntp state=restarted

#     - name: force ntp update
#       shell: "service ntp stop && ntpdate -s {{ hostvars[groups[timelord][0]]['ansible_' ~ ntp_netdevice]['ipv4']['address'] }} && service ntp start"
#       when: ansible_hostname != timelord

- name: disable selinux (not recommended in real setup for security reasons)
  selinux:
    state: disabled
  become: yes

# ntp
# firewalld
