---
- name: Base setup for all nodes in cluster
  hosts: all
  roles:
    - common
    - hadoop_os

- name: ambari server setup
  hosts: ambari-server
  roles:
   - ambari-server

- name: ambari agent setup
  hosts: ambari-
  roles:
   - ambari-client

- name: Install Snappy all nodes in cluster
  hosts: all
  roles:
    - hadoop_addon
