
- name: Create helper variables for the ambari server
  hosts: ambari-server
  gather_facts: False
  tasks:
    - name: Initialize the control variables
      set_fact:
        namenode_groups: []
        zkfc_groups: []
        resourcemanager_groups: []
        journalnode_groups: []
        zookeeper_groups: []
        zookeeper_hosts: []
        hiveserver_hosts: []
        oozie_hosts: []
        blueprint_all_services: []
        blueprint_all_clients: []
      no_log: True

    - block:
      - name: Populate the namenode groups list
        set_fact:
          namenode_groups: "{{ namenode_groups }} + [ '{{ item.host_group }}' ]"
        when: groups[item.host_group] is defined and groups[item.host_group]|length > 0 and 'NAMENODE' in item.services
        with_items: "{{ blueprint_dynamic }}"
        no_log: True

      - name: Populate the ZKFailoverController groups list
        set_fact:
          zkfc_groups: "{{ zkfc_groups }} + [ '{{ item.host_group }}' ]"
        when: groups[item.host_group] is defined and groups[item.host_group]|length > 0 and 'ZKFC' in item.services
        with_items: "{{ blueprint_dynamic }}"
        no_log: True

      - name: Populate the resourcemanager groups list
        set_fact:
          resourcemanager_groups: "[ '{{ item.host_group }}' ] + {{ resourcemanager_groups }}"
        when: groups[item.host_group] is defined and groups[item.host_group]|length > 0 and 'RESOURCEMANAGER' in item.services
        with_items: "{{ blueprint_dynamic }}"
        no_log: True

      - name: Populate the journalnode groups list
        set_fact:
          journalnode_groups: "{{ journalnode_groups }} + [ '{{ item.host_group }}' ]"
        when: groups[item.host_group] is defined and groups[item.host_group]|length > 0 and 'JOURNALNODE' in item.services
        with_items: "{{ blueprint_dynamic }}"
        no_log: True

      - name: Populate the zookeeper groups list
        set_fact:
          zookeeper_groups: "{{ zookeeper_groups }} + [ '{{ item.host_group }}' ]"
        when: groups[item.host_group] is defined and groups[item.host_group]|length > 0 and 'ZOOKEEPER_SERVER' in item.services
        with_items: "{{ blueprint_dynamic }}"
        no_log: True

      - name: Populate the zookeeper hosts list
        set_fact:
          zookeeper_hosts: "{{ zookeeper_hosts }} + {{ groups[item.host_group] }}"
        when: groups[item.host_group] is defined and groups[item.host_group]|length > 0 and 'ZOOKEEPER_SERVER' in item.services
        with_items: "{{ blueprint_dynamic }}"
        no_log: True

      - name: Populate the hiveserver hosts list
        set_fact:
          hiveserver_hosts: "{{ hiveserver_hosts }} + [ '{{ item.host_group }}' ]"
        when: groups[item.host_group] is defined and groups[item.host_group]|length > 0 and ('HIVE_SERVER' in item.services or 'HIVE_METASTORE' in item.services)
        with_items: "{{ blueprint_dynamic }}"
        no_log: True

      - name: Populate the oozie hosts list
        set_fact:
          oozie_hosts: "{{ oozie_hosts }} + [ '{{ item.host_group }}' ]"
        when: groups[item.host_group] is defined and groups[item.host_group]|length > 0 and ('OOZIE_SERVER' in item.services)
        with_items: "{{ blueprint_dynamic }}"
        no_log: True

      - name: Populate the all services and clients lists
        set_fact:
          blueprint_all_services: "{{ blueprint_all_services | union(item.services) }}"
          blueprint_all_clients: "{{ blueprint_all_clients | union(item.clients) }}"
        when: groups[item.host_group] is defined and groups[item.host_group]|length > 0
        with_items: "{{ blueprint_dynamic }}"
        no_log: True
