---
- name: Base setup for all nodes in cluster
  hosts: all
  roles:
    - common
    - hadoop_os
    - pyspark_addon

- name: ambari server setup
  hosts: ambari-server
  roles:
   - ambari-server

- name: ambari agent setup
  hosts: all
  roles:
   - ambari-client

- name: Install Snappy all nodes in cluster
  hosts: all
  roles:
    - hadoop_addon


# curl -H "X-Requested-By: ambari" -X GET -u admin:admin http://c6401.ambari.apache.org:8080/api/v1/blueprints

# export HIVE_CONF_DIR=/etc/hive/conf/conf.server


# sudo yum install mysql-connector-java*
# ls -al /usr/share/java/mysql-connector-java.jar
# cd /var/lib/ambari-server/resources/
# ln -s /usr/share/java/mysql-connector-java.jar mysql-connector-java.jar
