#
# Global variables for all nodes
#
---
host_arch: amd64

is_online: yes

# force ansible inventory hostname to be the actual node's hostname
ansibe_hostname_as_actual: yes

# the list of users to create with support for passwordless login within the cluster
passwordless_ssh_users:
  - name: root
    sudoer: no
    passwordless: yes
    home_dir: /root
  - name: sysadmin
    sudoer: yes
    passwordless: yes

ambari_version: 2.6.2.2
hdp_version: 2.6.5.0
