# tasks for ambari client role
---
- name: install ambari-agent
  yum:
    name: ambari-agent
    update_cache: yes
    state: latest
  notify: Reload systemd
  become: yes

- name: set the ambari server in the agent configuration
  lineinfile:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "^hostname="
    line: "hostname={{ hostvars[groups['ambari-server']|sort|list|first]['ansible_fqdn'] }}"
    state: present
  notify: Restart ambari-agent
  become: yes

### The following is done on Python >= 2.7 to prevent issues with the latest Python libraries rejecting lower TLS protocols
- name: Configure the Ambari Agents to use TLS 1.2
  ini_file:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    create: no
    section: "security"
    option: "force_https_protocol"
    value: "PROTOCOL_TLSv1_2"
    state: present
  notify: Restart ambari-agent
  become: yes
  when: (ansible_python_version is version_compare('2.7.9', '>=') and ansible_os_family|lower == "debian") or
        (ansible_python_version is version_compare('2.7', '>=') and ((ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int >= 7) or
                                                                     (ansible_os_family|lower == "suse" and ansible_distribution_major_version|int >= 12) or
                                                                     (ansible_os_family|lower == "redhat" and ansible_distribution|lower == "amazon")))

- meta: flush_handlers

- name: enable ambari-agent service
  systemd:
    name: ambari-agent
    enabled: yes
  ignore_errors: true
  become: yes

- name: start the ambari-agent service
  systemd:
    name: ambari-agent
    state: started
  become: yes

# Confirm the Agent hosts are registered with the Server.
# http://your.ambari.server:8080/api/v1/hosts

